### ISSUE TITLE
[Error] Log guild and builds

### ISSUE THREAD

**Issue by Zalatis** [Archomeda/kormir-discord-bot#3]
So I have enable the log_guild and builds options and got it 

```
Reading RSS feed https://forum-fr.guildwars2.com/forum/info/updates.rss
Unhandled rejection Error: Status 400
    at handleError (/discordbot/node_modules/lets-fetch/build/index.js:117:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

Got live build: 79386
Got RSS feed request response: 200
Got live latest release notes thread: http://forum-fr.guildwars2.com/forum/info/updates/Mise-jour-du-jeu-11-juillet-2017
Reading RSS feed http://forum-fr.guildwars2.com/forum/info/updates/Mise-jour-du-jeu-11-juillet-2017.rss
Got RSS feed request response: 200
Number of found live release notes in latest release notes thread: 5
```

-------------------------------------------------------------------------------
The problem is that the bot says nothing to the channel who I setup

- And a small question, how to setup correctly the permission like for addevent command ? 
- There is also a problem with permission for me, can you explain how to setup permissions correctly ? 

Very good work for this bot :)

**Comment by Archomeda** [comment]
Hey there, thanks for taking your time to try out my bot, and sorry for my late response. I haven't really looked at GitHub for a while.

I assume you're using the `master` branch? There are some issues that are solved in the `refactor` branch. The structure has also been changed a lot, especially the configuration files.

I'll try my best to solve whatever is happening right now, and further below I'll explain what will be changed once I merge the `refactor` branch into `master`. If you have any questions after this, ask away ;)

### Update notifications ###
I see that in your log, there's a 400, which is nothing you have to worry about. It's just a failed request to the RSS feed. Although that unhandled rejection is completely my fault, it's harmless.
Later it did get the latest build and release notes, and as you can see, it got 5 forum posts in that thread.

However, the reason you might not be seeing anything immediately, is because you probably didn't run the bot for a while. Basically, when it starts up, it checks for the latest data. If the bot doesn't know anything what the previous data was (in this case, the previous build or release notes), it won't post a notification in the discord channel.
If you use redis (or docker), this happens only the first time you start the bot. Restarts will not influence this in any way because the data is cached in redis. However, if you don't use redis, it will happen every time you restart the bot, because the cache is not persistent.

Once a new build is released or new release notes are available, the bot should proceed to post it in the appropriate discord channel. That is, if the bot has permissions to post in that channel.

If the bot still refuses to post anything, please reply with the contents of your `local.yml` file. **But  remove any personal information and API keys or tokens before doing so.**

### Command permissions ###
I understand that the information I added in the config file might not be clear the first time.

Basically, you put accounts and/or roles into one or groups. You have to use their numeric ID for that (one option to get that is by typing `@<name-or-role>` with a backslash in front of it, e.g. `\@<name-or-role>`).

Let's say, we got a role *event-manager*, and we want to add everyone that's part of the discord role `moderator` (that has ID 1234567890). It will end up like this:

```yml
permissions:
  event-manager:
    user-ids: [] # Empty list, as we don't have specific users
    role-ids:
      - "1234567890" # Has to be a string (double quotes around it), because the IDs are too long for a number that Javascript can handle sadly
```

Now we want to make sure that they can use the event commands. For that, we have to add the command ids to the whitelist:

```yml
permissions:
  event-manager:
    user-ids: []
    role-ids:
      - "1234567890"
    blacklist: [] # I'll explain this below
    whitelist:
      - schedule.add-event
      - schedule.edit-event:own # Only allow editing their own events, otherwise remove
      - schedule.delete-event:own # Only allow deleting their own events, otherwise remove
```

As you can see, the only commands listed are the schedule commands in the whitelist. Our blacklist is empty because we don't have to blacklist anything specifically for them. If a command is executed that doesn't match any of these, it will fall back to the other groups that the user or the role is part of. If there isn't anything else, it will fall back to the `default` group (don't delete this!).

If the command is available in any of the fall back groups (or default group) it will either blacklist or whitelist the command for them, based on what's configured there.

If you have issues making yourself part of the *owner* group, check if you got the correct ID of your discord account added to the `user-ids` property, like this:

```yml
permissions:
  owner:
    user-ids:
      - "0987654321" # This account ID is just an example
    role-ids: []
    blacklist: [] # Nothing to blacklist
    whitelist:
      - "*" # Whitelist all the things
      - "*:*" # Also whitelist all the sub permissions of commands
```

**Please note that I've left out other possible groups (and the default group) on purpose for clarity. You must not do that in your own config file.**

### Changes in configuration files on the `refactor` branch ###
Right now, it works like this: you copy [`config/default.yml`](https://github.com/Archomeda/kormir-discord-bot/blob/f338c58e54c5b7afbe17c511fe3ff419075df038/config/default.yml) to `config/local.yml` and make changes. Any config property that hasn't been found, will default to whatever default.yml says.
local.yml is not pushed to a repository and may contain personal information, whereas default.yml may not.

After I merge the `refactor` branch, it will work differently. I've moved a lot of code to the `bot` folder that can be shared between multiple bot repositories (as a way of sharing code, I still have to separate it completely and make it a module or something). Therefore, anything that's in that folder, defaults to all bots that inherit that code. There's [`bot/config/default.yml`](https://github.com/Archomeda/kormir-discord-bot/blob/e44ddd398aec6b19f6d62457043b0bcd9c482ca9/bot/config/default.yml) that contains default settings for *all* bot repositories. The configuration for a single bot repository is located at [`config/default.yml`](https://github.com/Archomeda/kormir-discord-bot/blob/e44ddd398aec6b19f6d62457043b0bcd9c482ca9/config/default.yml) and may or may not contain overrides of `bot/config/default.yml`. Of course, there's also still `config/local.yml` that works the same way as previously.
Anything that's not defined in `config/local.yml`, will be loaded from `config/default.yml`. And anything that's not defined in `config/default.yml`, will be loaded from `bot/config/default.yml`.

Some settings have been moved around as well, or flat-out removed. You have to compare the [`master` branch version](https://github.com/Archomeda/kormir-discord-bot/blob/f338c58e54c5b7afbe17c511fe3ff419075df038/config/default.yml) to both `refactor` branch versions: [global config](https://github.com/Archomeda/kormir-discord-bot/blob/e44ddd398aec6b19f6d62457043b0bcd9c482ca9/bot/config/default.yml), [app config](https://github.com/Archomeda/kormir-discord-bot/blob/e44ddd398aec6b19f6d62457043b0bcd9c482ca9/config/default.yml).
